# Generated by Django 5.2 on 2025-04-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tiffin_images/'),
        ),
    ]
